/*
  File: models/Report.js
  Purpose: Define Mongoose schema for analytical or compliance reports generated by the system.
*/
const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  title: { type: String, required: true, trim: true },
  stock: { type: mongoose.Schema.Types.ObjectId, ref: 'Stock', required: true },
  content: { type: String, required: true },
  analyst: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

  // ảnh minh họa (VD: biểu đồ, phân tích kỹ thuật)
  chartImage: { type: String }, // URL hình biểu đồ
  attachment: { type: String }, // PDF hoặc file đính kèm phân tích chi tiết

  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Report', reportSchema);
